---
# ========================
#     GENERAL CONFIG
# ========================
# Instructions: In 'general souls mode' you can use 1 for money and 2 for XP.
# Protip: Use Minecraft color-coded symbols to customize your messages.

in-game-message: "§cUse this command in-game."
no-perms-message: "§cYou don't have permission to use this command."
command-not-available: "§cThis command is not available for you to use now."

general-price-per-soul: 1 
general-souls-sell-mode: 1

message-success-when-selling: "§aYou sold your souls successfully." 
message-not-enough-souls: "§cYou don't have enough souls to sell."

souls-per-player-kill: 1
souls-worlds-give: ["world", "arena"]

# ========================
#     COMMANDS OPTION
# ========================
# Instructions: Set to false to disable command features on your server.

souls-view-command: true
souls-sell-command: true
souls-manage-command: true

# ========================
#     COMMANDS CONFIG
# ========================
# Instructions: Do not use spaces in the command name and Minecraft color codes aren't recommended.
# You can use {player_souls} to get all player souls and {player_name} to get the player name.

souls-view-command-name: "souls"
souls-view-command-description: "View your total souls on the server."
souls-view-message-command: "§aYou have §6{player_souls} §8souls."

souls-sell-command-name: "soulsell"
souls-sell-command-description: "Sell your souls for money or XP on the server."

# ========================
#    SOULS FORM CONFIG
# ========================
# Protip: Use Minecraft color-coded symbols to customize your messages and \n to break a line.
# Instructions: You can use {player_souls} to get all player souls and {player_name} to get the player name.

form-souls-sell-title: "§l§8SOULS SELL"
form-souls-sell-description: "§fYou have §6{player_souls} §fsouls to sell."
form-souls-sell-exit: "§l§aSELL\n§8Click to sell your souls."
form-souls-sell-exit-button: "§l§cEXIT\n§8Click to exit from souls sell form."
...